//
// DeviceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum DeviceType: String, Codable {
    case wave = "WAVE"
    case waveMist = "WAVE_MIST"
    case waveGen2 = "WAVE_GEN2"
    case waveMini = "WAVE_MINI"
    case wavePlus = "WAVE_PLUS"
    case waveCo2 = "WAVE_CO2"
    case viewPlus = "VIEW_PLUS"
    case viewPlusBusiness = "VIEW_PLUS_BUSINESS"
    case viewPollution = "VIEW_POLLUTION"
    case viewRadon = "VIEW_RADON"
    case viewCo2 = "VIEW_CO2"
    case ternCo2 = "TERN_CO2"
    case hub = "HUB"
    case home = "HOME"
    case pro = "PRO"
    case cloudberry = "CLOUDBERRY"
    case airtight = "AIRTIGHT"
    case aggregatedGroup = "AGGREGATED_GROUP"
    case zoneGroup = "ZONE_GROUP"
    case balanceControl = "BALANCE_CONTROL"
    case inletAirControl = "INLET_AIR_CONTROL"
    case ventController = "VENT_CONTROLLER"
    case airly = "AIRLY"
    case airlyNo2 = "AIRLY_NO2"
    case airlyCo = "AIRLY_CO"
    case airlyNo = "AIRLY_NO"
    case breezometerWeather = "BREEZOMETER_WEATHER"
    case bacnet = "BACNET"
    case unknown = "UNKNOWN"
}