//
// DeviceSampleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceSampleResponse: Codable {

    public var data: SingleSampleData

    public init(_id: String, data: SingleSampleData) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case data
    }

}
