//
// GetDeviceDetailedResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct GetDeviceDetailedResponse: Codable {

    public var _id: String
    public var deviceType: DeviceType
    public var sensors: [SensorType]

    public init(_id: String, deviceType: DeviceType, sensors: [SensorType] ) {
        self._id = _id
        self.deviceType = deviceType
        self.sensors = sensors
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case deviceType
        case sensors
    }

}
