//
// GetDevicesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetDevicesResponse: Codable {

    public var devices: [GetDeviceDetailedResponse]?

    public init(devices: [GetDeviceDetailedResponse]? = nil) {
        self.devices = devices
    }


}
