//
// GetLocationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLocationResponse: Codable {

    public enum BuildingType: String, Codable { 
        case school = "SCHOOL"
        case residential = "RESIDENTIAL"
        case apartment = "APARTMENT"
        case kindergarten = "KINDERGARTEN"
        case healthcenter = "HEALTHCENTER"
        case office = "OFFICE"
        case other = "OTHER"
    }
    public enum VentilationType: String, Codable { 
        case natural = "NATURAL"
        case mechanical = "MECHANICAL"
        case balanced = "BALANCED"
    }
    public var _id: String
    public var name: String
    public var labels: [String:String]
    public var devices: [DeviceSimpleResponse]
    public var address: String?
    public var countryCode: String?
    public var lat: Float
    public var lng: Float
    public var buildingType: BuildingType?
    public var buildingYear: Int?
    public var ventilationType: VentilationType?
    public var timezone: String?
    public var usageHours: [String:LocationUsage]?
    public var buildingHeight: Float?
    public var buildingSize: Float?
    public var buildingVolume: Float?
    public var floors: Int?

    public init(_id: String, name: String, labels: [String:String], devices: [DeviceSimpleResponse], address: String? = nil, countryCode: String? = nil, lat: Float, lng: Float, buildingType: BuildingType? = nil, buildingYear: Int? = nil, ventilationType: VentilationType? = nil, timezone: String? = nil, usageHours: [String:LocationUsage]? = nil, buildingHeight: Float? = nil, buildingSize: Float? = nil, buildingVolume: Float? = nil, floors: Int? = nil) {
        self._id = _id
        self.name = name
        self.labels = labels
        self.devices = devices
        self.address = address
        self.countryCode = countryCode
        self.lat = lat
        self.lng = lng
        self.buildingType = buildingType
        self.buildingYear = buildingYear
        self.ventilationType = ventilationType
        self.timezone = timezone
        self.usageHours = usageHours
        self.buildingHeight = buildingHeight
        self.buildingSize = buildingSize
        self.buildingVolume = buildingVolume
        self.floors = floors
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case labels
        case devices
        case address
        case countryCode
        case lat
        case lng
        case buildingType
        case buildingYear
        case ventilationType
        case timezone
        case usageHours
        case buildingHeight
        case buildingSize
        case buildingVolume
        case floors
    }

}
