//
// GetLocationsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLocationsResponse: Codable {

    public var locations: [Location]

    public init(locations: [Location]) {
        self.locations = locations
    }


}
