//
// LocalTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LocalTime: Codable {

    public var hour: Int?
    public var minute: Int?
    public var second: Int?
    public var nano: Int?

    public init(hour: Int? = nil, minute: Int? = nil, second: Int? = nil, nano: Int? = nil) {
        self.hour = hour
        self.minute = minute
        self.second = second
        self.nano = nano
    }


}
