//
// LocationUsage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LocationUsage: Codable {

    public var closed: Bool?
    public var from: LocalTime?
    public var to: LocalTime?
    public var nofMinutesOpen: Int?

    public init(closed: Bool? = nil, from: LocalTime? = nil, to: LocalTime? = nil, nofMinutesOpen: Int? = nil) {
        self.closed = closed
        self.from = from
        self.to = to
        self.nofMinutesOpen = nofMinutesOpen
    }


}
