//
// SegmentSimpleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SegmentSimpleResponse: Codable {

    public var _id: String
    public var name: String
    public var started: Date
    public var active: Bool

    public init(_id: String, name: String, started: Date, active: Bool) {
        self._id = _id
        self.name = name
        self.started = started
        self.active = active
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case started
        case active
    }

}
