//
// SingleSampleData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SingleSampleData: Codable {

    public var battery: Int?
    public var co2: Double?
    public var humidity: Double?
    public var light: Int?
    public var mold: Double?
    public var pm1: Double?
    public var pm10: Double?
    public var pm25: Double?
    public var pressure: Double?
    public var pressureDifference: Double?
    public var radonShortTermAvg: Double?
    public var rssi: Int?
    public var sla: Double?
    public var temp: Double?
    public var time: Int?
    public var virusRisk: Double?
    public var voc: Double?
    public var outdoorTemp: Double?
    public var outdoorHumidity: Double?
    public var outdoorPressure: Double?
    public var outdoorPm10: Double?
    public var outdoorPm1: Double?
    public var outdoorPm25: Double?
    public var outdoorNo2: Double?
    public var outdoorO3: Double?
    public var outdoorSo2: Double?
    public var outdoorCo: Double?
    public var outdoorNo: Double?
    public var controlSignal: Double?
    public var controlSignalSlot01: Double?
    public var controlSignalSlot02: Double?
    public var controlSignalSlot03: Double?
    public var controlSignalSlot04: Double?
    public var controlSignalSlot05: Double?
    public var controlSignalSlot06: Double?
    public var controlSignalSlot07: Double?
    public var controlSignalSlot08: Double?
    public var regulationPressure: Double?
    public var regulationHeight: Double?
    public var relayDeviceType: String?

    public init(battery: Int? = nil, co2: Double? = nil, humidity: Double? = nil, light: Int? = nil, mold: Double? = nil, pm1: Double? = nil, pm10: Double? = nil, pm25: Double? = nil, pressure: Double? = nil, pressureDifference: Double? = nil, radonShortTermAvg: Double? = nil, rssi: Int? = nil, sla: Double? = nil, temp: Double? = nil, time: Int? = nil, virusRisk: Double? = nil, voc: Double? = nil, outdoorTemp: Double? = nil, outdoorHumidity: Double? = nil, outdoorPressure: Double? = nil, outdoorPm10: Double? = nil, outdoorPm1: Double? = nil, outdoorPm25: Double? = nil, outdoorNo2: Double? = nil, outdoorO3: Double? = nil, outdoorSo2: Double? = nil, outdoorCo: Double? = nil, outdoorNo: Double? = nil, controlSignal: Double? = nil, controlSignalSlot01: Double? = nil, controlSignalSlot02: Double? = nil, controlSignalSlot03: Double? = nil, controlSignalSlot04: Double? = nil, controlSignalSlot05: Double? = nil, controlSignalSlot06: Double? = nil, controlSignalSlot07: Double? = nil, controlSignalSlot08: Double? = nil, regulationPressure: Double? = nil, regulationHeight: Double? = nil, relayDeviceType: String? = nil) {
        self.battery = battery
        self.co2 = co2
        self.humidity = humidity
        self.light = light
        self.mold = mold
        self.pm1 = pm1
        self.pm10 = pm10
        self.pm25 = pm25
        self.pressure = pressure
        self.pressureDifference = pressureDifference
        self.radonShortTermAvg = radonShortTermAvg
        self.rssi = rssi
        self.sla = sla
        self.temp = temp
        self.time = time
        self.virusRisk = virusRisk
        self.voc = voc
        self.outdoorTemp = outdoorTemp
        self.outdoorHumidity = outdoorHumidity
        self.outdoorPressure = outdoorPressure
        self.outdoorPm10 = outdoorPm10
        self.outdoorPm1 = outdoorPm1
        self.outdoorPm25 = outdoorPm25
        self.outdoorNo2 = outdoorNo2
        self.outdoorO3 = outdoorO3
        self.outdoorSo2 = outdoorSo2
        self.outdoorCo = outdoorCo
        self.outdoorNo = outdoorNo
        self.controlSignal = controlSignal
        self.controlSignalSlot01 = controlSignalSlot01
        self.controlSignalSlot02 = controlSignalSlot02
        self.controlSignalSlot03 = controlSignalSlot03
        self.controlSignalSlot04 = controlSignalSlot04
        self.controlSignalSlot05 = controlSignalSlot05
        self.controlSignalSlot06 = controlSignalSlot06
        self.controlSignalSlot07 = controlSignalSlot07
        self.controlSignalSlot08 = controlSignalSlot08
        self.regulationPressure = regulationPressure
        self.regulationHeight = regulationHeight
        self.relayDeviceType = relayDeviceType
    }


}
