//
// SingleSampleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SingleSampleResponse: Codable {

    public var data: SingleSampleData?

    public init(data: SingleSampleData? = nil) {
        self.data = data
    }


}
